apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lagoon-logging.logsDispatcher.selectorLabels" . | nindent 4 }}
  ports:
  - name: forward
    port: 24224
    protocol: TCP
    targetPort: 24224
  - name: metrics
    port: 24231
    protocol: TCP
    targetPort: 24231
