apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-env
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
data:
  CLUSTER_NAME: {{ required "A valid .Values.clusterName required!" .Values.clusterName }}
  ELASTICSEARCH_HOST: {{ required "A valid .Values.elasticsearchHost required!" .Values.elasticsearchHost }}
  ELASTICSEARCH_HOST_PORT: {{ .Values.elasticsearchHostPort | quote }}
  ELASTICSEARCH_SCHEME: {{ .Values.elasticsearchScheme }}
