{{- if .Values.logsTeeRouter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-logging.logsTeeRouter.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsTeeRouter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lagoon-logging.logsTeeRouter.selectorLabels" . | nindent 4 }}
  ports:
  - name: syslog-router
    port: {{ .Values.logsTeeRouter.listenPort }}
    protocol: UDP
    targetPort: syslog-router
{{- end }}
{{- if .Values.logsTeeApplication.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-logging.logsTeeApplication.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsTeeApplication.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lagoon-logging.logsTeeApplication.selectorLabels" . | nindent 4 }}
  ports:
  - name: application
    port: {{ .Values.logsTeeApplication.listenPort }}
    protocol: UDP
    targetPort: application
{{- end }}
