{{- if .Values.logsDispatcher.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.serviceAccountName" . }}
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
  {{- with .Values.logsDispatcher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
