apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.logsDispatcher.replicaCount }}
  serviceName: {{ include "lagoon-logging.logsDispatcher.fullname" . }}
  selector:
    matchLabels:
      {{- include "lagoon-logging.logsDispatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.logsDispatcher.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-logging.logsDispatcher.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagoon-logging.logsDispatcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.logsDispatcher.podSecurityContext | nindent 8 }}
      initContainers:
      - image: busybox:musl
        imagePullPolicy: Always
        name: chown-buffer
        command:
        - chown
        - '100:0'
        - /fluentd/buffer
        volumeMounts:
        - mountPath: /fluentd/buffer/
          name: buffer
      containers:
      - name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-fluentd
        securityContext:
          {{- toYaml .Values.logsDispatcher.securityContext | nindent 10 }}
        image: "{{ .Values.logsDispatcher.image.repository }}:{{ .Values.logsDispatcher.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.logsDispatcher.image.pullPolicy }}
        ports:
        - containerPort: 24224
          protocol: TCP
          name: forward
        - containerPort: 24231
          protocol: TCP
          name: metrics
        - containerPort: 5140
          protocol: UDP
          name: application
        - containerPort: 5141
          protocol: UDP
          name: syslog-router
        readinessProbe:
          tcpSocket:
            port: 24224
          initialDelaySeconds: 20
        livenessProbe:
          tcpSocket:
            port: 24224
          initialDelaySeconds: 120
        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-fluent-conf
          subPath: fluent.conf
        {{- if .Values.exportLogs }}
        - mountPath: /fluentd/etc/store.d
          name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-store
        {{- end }}
        {{- if .Values.lagoonLogs.enabled }}
        - mountPath: /fluentd/etc/source.d
          name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-source-lagoon
        {{- end }}
        - mountPath: /fluentd/buffer/
          name: buffer
        - mountPath: /fluentd/tls/
          name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-tls
        envFrom:
        - secretRef:
            name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-env
        - configMapRef:
            name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-env
        resources:
          {{- toYaml .Values.logsDispatcher.resources | nindent 10 }}
      {{- with .Values.logsDispatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logsDispatcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logsDispatcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: fluent.conf
            path: fluent.conf
          name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-fluent-conf
        name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-fluent-conf
      {{- if .Values.exportLogs }}
      - configMap:
          defaultMode: 420
          name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-store
        name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-store
      {{- end }}
      - secret:
          defaultMode: 420
          secretName: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-tls
        name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-tls
  volumeClaimTemplates:
  - metadata:
      name: buffer
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
