{{- if .Values.exportLogs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-store
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.exportLogs | nindent 2 }}
{{- end }}
