# Lagoon Version Update Helper
#
# Helper to update Version inside Dockerfiles
# Update versions below in `vars` and execute locally
#
# ansible-playbook helpers/update-versions.yml
- name: update versions
  hosts: 127.0.0.1
  connection: local
  vars:
    # Newrelic - https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/
    NEWRELIC_VERSION: '9.11.0.267'
    # Composer - https://getcomposer.org/download/
    COMPOSER_VERSION: '1.10.7'
    COMPOSER_HASH_SHA256: 'b94b872729668de5b5fbf62f16ff588d2a23480dda88c0e45cb43b721b75ae29'
    # Drupal Console Launcher - https://github.com/hechoendrupal/drupal-console-launcher/releases
    DRUPAL_CONSOLE_LAUNCHER_VERSION: 1.9.4
    DRUPAL_CONSOLE_LAUNCHER_SHA: b7759279668caf915b8e9f3352e88f18e4f20659
    # Drush - https://github.com/drush-ops/drush/releases
    DRUSH_VERSION: 8.3.5
    # Drush Launcher Version - https://github.com/drush-ops/drush-launcher/releases
    DRUSH_LAUNCHER_VERSION: 0.6.0
  tasks:
  - name: update NEWRELIC_VERSION
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/fpm/Dockerfile"
        regexp: 'ENV NEWRELIC_VERSION='
        line: 'ENV NEWRELIC_VERSION={{ NEWRELIC_VERSION }}'
  - name: update COMPOSER_VERSION
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/cli/Dockerfile"
        regexp: 'ENV COMPOSER_VERSION='
        line: 'ENV COMPOSER_VERSION={{ COMPOSER_VERSION }} \'
  - name: update COMPOSER_HASH_SHA256
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/cli/Dockerfile"
        regexp: 'COMPOSER_HASH_SHA256='
        line: '  COMPOSER_HASH_SHA256={{ COMPOSER_HASH_SHA256 }}'
  - name: update DRUPAL_CONSOLE_LAUNCHER_VERSION
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/cli-drupal/Dockerfile"
        regexp: 'ENV DRUPAL_CONSOLE_LAUNCHER_VERSION='
        line: 'ENV DRUPAL_CONSOLE_LAUNCHER_VERSION={{ DRUPAL_CONSOLE_LAUNCHER_VERSION }} \'
  - name: update DRUPAL_CONSOLE_LAUNCHER_SHA
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/cli-drupal/Dockerfile"
        regexp: 'DRUPAL_CONSOLE_LAUNCHER_SHA='
        line: '    DRUPAL_CONSOLE_LAUNCHER_SHA={{ DRUPAL_CONSOLE_LAUNCHER_SHA }} \'
  - name: update DRUSH_VERSION
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/cli-drupal/Dockerfile"
        regexp: 'DRUSH_VERSION='
        line: '    DRUSH_VERSION={{ DRUSH_VERSION }} \'
  - name: update DRUSH_LAUNCHER_VERSION
    lineinfile:
        path: "{{ lookup('env', 'PWD') }}/images/php/cli-drupal/Dockerfile"
        regexp: 'DRUSH_LAUNCHER_VERSION='
        line: '    DRUSH_LAUNCHER_VERSION={{ DRUSH_LAUNCHER_VERSION }} \'
