apiVersion: v1
entries:
  lagoon-logging:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-05-20T21:04:11.988795-04:00"
    dependencies:
    - name: logging-operator
      repository: https://kubernetes-charts.banzaicloud.com
      version: ~3.0.5
    description: |
      A Helm chart for Kubernetes which installs the lagoon container and router logs collection system.
    digest: 974f04650815b54aacbafcd4539058f7ad4d3d384604b16236e78abe8b5935e1
    name: lagoon-logging
    type: application
    urls:
    - lagoon-logging-0.1.0.tgz
    version: 0.1.0
  lagoon-remote:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2020-05-20T21:04:11.990249-04:00"
    description: A Helm chart to run a lagoon-remote
    digest: 96bc41bc9985cd6a7fbd85a32affea3bbbabdf4baa0cd829e7e3d33fb975ceeb
    name: lagoon-remote
    type: application
    urls:
    - lagoon-remote-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2020-05-20T21:04:11.989691-04:00"
    description: A Helm chart to run a lagoon-remote
    digest: 5756a3fbb46a11f2f43fdcadb41d709d90c70208b90fa0257d48dcacc4df3040
    name: lagoon-remote
    type: application
    urls:
    - lagoon-remote-0.1.2.tgz
    version: 0.1.2
generated: "2020-05-20T21:04:11.982298-04:00"
